import { Injectable, signal } from '@angular/core';

export type Lang = 'UA' | 'EN' | 'IT' | 'DE' | 'FR';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  currentLang = signal<Lang>('UA');

  translations: Record<Lang, any> = {
    UA: {
      nav: { menu: "МЕНЮ", contact: "КОНТАКТИ", tea: "ЧАЙ" },
      hero: { title: "НАША СЕЛЕКЦІЯ" },
      tea: {
        title: "КИТАЙСЬКА ЧАЙНА ЦЕРЕМОНІЯ",
        subtitle: "Ціна: 300 грн",
        description: "Зануртесь у атмосферу спокою та гармонії. У нас представлено понад 40 видів справжнього китайського чаю. Відкрийте для себе тисячолітні традиції чаювання.",
        features: ["Зелений чай", "Улун", "Червоний Чай", "Білий Чай", "Шен Пуер", "Шу Пуер"]
      },
      visit: { title: "ЗАВІТАЙТЕ ДО НАС", address: "вул. Лесі Українки, 38", city: "Кам'янець-Подільський", route: "МАРШРУТ" },
      items: {
        sh_chicken: "Шаурма курка",
        sh_beef: "Шаурма яловичина",
        sh_double: "Шаурма подвійна",
        sh_greek: "Шаурма грецька",
        snd_pork: "Сендвіч стандарт (буженіна)",
        snd_chicken: "Сендвіч стандарт (курка)",
        brg_classic: "Бургер Класик (яловичина)",
        brg_cheese: "Чізбургер (яловичина)",
        brg_chicken: "Чікенбургер (курка)",
        brg_d_classic: "Дабл Бургер Класик (яловичина)",
        brg_d_cheese: "Дабл Чізбургер (яловичина)",
        brg_d_chicken: "Дабл Чікен Бургер (курка)",
        brg_mega: "Мега Бургер XXL",
        hd_white_m: "Хот Дог світла булка (мол. сосиска)",
        hd_dark_m: "Хот Дог темна булка (мол. сосиска)",
        hd_white_d: "Хот Дог світла булка (темна ковбаска)",
        hd_dark_d: "Хот Дог темна булка (темна ковбаска)",
        fries_100: "Картопля фрі хрустка (100 г)",
        fries_150: "Картопля фрі хрустка (150 г)",
        nuggets_7: "Курячі нагетси (7 шт)",
        nuggets_10: "Курячі нагетси (10 шт)",
        cheese_sticks: "Сирні палички",
        mix_plate: "Мікс картопля та ковбаска",
        cr_choc: "Круасан з шоколадом",
        cr_caramel: "Круасан з солоною карамеллю",
        donuts: "Донати",
        macaroon: "Макарун",
        tube: "Трубочка",
        eclair: "Еклер",
        waffles: "Бельгійські вафлі з фруктами",
        cola: "Coca-Cola",
        fanta: "Fanta",
        sprite: "Sprite",
        bonakva: "Bonakva",
        sauce_cheese: "Соус Сирний",
        sauce_chili: "Соус Солодкий Чилі",
        sauce_bbq: "Соус Барбекю"
      },
      categories: {
        shawarma: "Шаурма",
        sandwiches: "Сендвічі",
        burgers: "Бургери",
        hotdogs: "Хот-доги",
        fry: "Фрітюр",
        desserts: "Десерти",
        drinks: "Напої",
        sauces: "Соуси"
      }
    },
    EN: {
      nav: { menu: "MENU", contact: "CONTACT", tea: "TEA" },
      hero: { title: "OUR SELECTION" },
      tea: {
        title: "CHINESE TEA CEREMONY",
        subtitle: "Price: 300 UAH",
        description: "Immerse yourself in an atmosphere of peace and harmony. We offer over 40 varieties of authentic Chinese tea. Discover millennia of tea traditions.",
        features: ["Green Tea", "Oolong", "Red Tea", "White Tea", "Sheng Puer", "Shu Puer"]
      },
      visit: { title: "VISIT US", address: "38 Lesi Ukrainki St.", city: "Kamianets-Podilskyi", route: "ROUTE" },
      items: {
        sh_chicken: "Chicken Shawarma",
        sh_beef: "Beef Shawarma",
        sh_double: "Double Shawarma",
        sh_greek: "Greek Shawarma",
        snd_pork: "Standard Sandwich (Pork)",
        snd_chicken: "Standard Sandwich (Chicken)",
        brg_classic: "Classic Burger (Beef)",
        brg_cheese: "Cheeseburger (Beef)",
        brg_chicken: "Chicken Burger",
        brg_d_classic: "Double Classic Burger",
        brg_d_cheese: "Double Cheeseburger",
        brg_d_chicken: "Double Chicken Burger",
        brg_mega: "Mega Burger XXL",
        hd_white_m: "Hot Dog White Bun (Milk Sausage)",
        hd_dark_m: "Hot Dog Dark Bun (Milk Sausage)",
        hd_white_d: "Hot Dog White Bun (Dark Sausage)",
        hd_dark_d: "Hot Dog Dark Bun (Dark Sausage)",
        fries_100: "Crispy Fries (100g)",
        fries_150: "Crispy Fries (150g)",
        nuggets_7: "Chicken Nuggets (7 pcs)",
        nuggets_10: "Chicken Nuggets (10 pcs)",
        cheese_sticks: "Cheese Sticks",
        mix_plate: "Mix Potato & Sausage Plate",
        cr_choc: "Chocolate Croissant",
        cr_caramel: "Salted Caramel Croissant",
        donuts: "Donuts",
        macaroon: "Macaroon",
        tube: "Sweet Tube",
        eclair: "Eclair",
        waffles: "Belgian Waffles with Fruit",
        cola: "Coca-Cola",
        fanta: "Fanta",
        sprite: "Sprite",
        bonakva: "Bonakva",
        sauce_cheese: "Cheese Sauce",
        sauce_chili: "Sweet Chili Sauce",
        sauce_bbq: "BBQ Sauce"
      },
      categories: {
        shawarma: "Shawarma",
        sandwiches: "Sandwiches",
        burgers: "Burgers",
        hotdogs: "Hot Dogs",
        fry: "Deep Fry",
        desserts: "Desserts",
        drinks: "Cold Drinks",
        sauces: "Sauces"
      }
    },
    IT: {
      nav: { menu: "MENU", contact: "CONTATTI", tea: "TÈ" },
      hero: { title: "LA NOSTRA SELEZIONE" },
      tea: {
        title: "CERIMONIA DEL TÈ CINESE",
        subtitle: "Prezzo: 300 UAH",
        description: "Immergiti in un'atmosfera di pace e armonia. Offriamo oltre 40 varietà di autentico tè cinese. Scopri millenni di tradizioni del tè.",
        features: ["Tè Verde", "Oolong", "Tè Rosso", "Tè Bianco", "Sheng Puer", "Shu Puer"]
      },
      visit: { title: "VIENI A TROVARCI", address: "Via Lesi Ukrainki, 38", city: "Kamianets-Podilskyi", route: "PERCORSO" },
      items: {
        sh_chicken: "Shawarma di Pollo",
        sh_beef: "Shawarma di Manzo",
        sh_double: "Shawarma Doppia",
        sh_greek: "Shawarma Greca",
        snd_pork: "Sandwich Standard (Maiale)",
        snd_chicken: "Sandwich Standard (Pollo)",
        brg_classic: "Burger Classico",
        brg_cheese: "Cheeseburger",
        brg_chicken: "Chicken Burger",
        brg_d_classic: "Double Classic Burger",
        brg_d_cheese: "Double Cheeseburger",
        brg_d_chicken: "Double Chicken Burger",
        brg_mega: "Mega Burger XXL",
        hd_white_m: "Hot Dog Pane Bianco",
        hd_dark_m: "Hot Dog Pane Nero",
        hd_white_d: "Hot Dog Salsiccia Scura",
        hd_dark_d: "Hot Dog Salsiccia Scura",
        fries_100: "Patatine Fritte (100g)",
        fries_150: "Patatine Fritte (150g)",
        nuggets_7: "Nuggets di Pollo (7pz)",
        nuggets_10: "Nuggets di Pollo (10pz)",
        cheese_sticks: "Bastoncini di Formaggio",
        mix_plate: "Piatto Misto Patate e Salsiccia",
        cr_choc: "Croissant al Cioccolato",
        cr_caramel: "Croissant al Caramello",
        donuts: "Donuts",
        macaroon: "Macaron",
        tube: "Cannolo Dolce",
        eclair: "Eclair",
        waffles: "Waffle Belgi con Frutta",
        cola: "Coca-Cola",
        fanta: "Fanta",
        sprite: "Sprite",
        bonakva: "Bonakva",
        sauce_cheese: "Salsa al Formaggio",
        sauce_chili: "Salsa Chili Dolce",
        sauce_bbq: "Salsa BBQ"
      },
      categories: {
        shawarma: "Shawarma",
        sandwiches: "Sandwich",
        burgers: "Burger",
        hotdogs: "Hot Dog",
        fry: "Frittura",
        desserts: "Dolci",
        drinks: "Bevande",
        sauces: "Salse"
      }
    },
    DE: {
      nav: { menu: "MENÜ", contact: "KONTAKT", tea: "TEE" },
      hero: { title: "UNSERE AUSWAHL" },
      tea: {
        title: "CHINESISCHE TEEZEREMONIE",
        subtitle: "Preis: 300 UAH",
        description: "Tauchen Sie ein in eine Atmosphäre der Ruhe und Harmonie. Wir bieten über 40 Sorten echten chinesischen Tees an. Entdecken Sie jahrtausendealte Teetraditionen.",
        features: ["Grüner Tee", "Oolong", "Roter Tee", "Weißer Tee", "Sheng Puer", "Shu Puer"]
      },
      visit: { title: "BESUCHEN SIE UNS", address: "Lesi Ukrainki Str. 38", city: "Kamjanez-Podilskyj", route: "ROUTE" },
      items: {
        sh_chicken: "Hähnchen Schawarma",
        sh_beef: "Rindfleisch Schawarma",
        sh_double: "Doppel Schawarma",
        sh_greek: "Griechisches Schawarma",
        snd_pork: "Sandwich (Schweinefleisch)",
        snd_chicken: "Sandwich (Hähnchen)",
        brg_classic: "Klassischer Burger",
        brg_cheese: "Cheeseburger",
        brg_chicken: "Chicken Burger",
        brg_d_classic: "Doppelter Klassik Burger",
        brg_d_cheese: "Doppelter Cheeseburger",
        brg_d_chicken: "Doppelter Chicken Burger",
        brg_mega: "Mega Burger XXL",
        hd_white_m: "Hot Dog Helles Brötchen",
        hd_dark_m: "Hot Dog Dunkles Brötchen",
        hd_white_d: "Hot Dog Helles Brötchen",
        hd_dark_d: "Hot Dog Dunkles Brötchen",
        fries_100: "Pommes Frites (100g)",
        fries_150: "Pommes Frites (150g)",
        nuggets_7: "Chicken Nuggets (7 Stk)",
        nuggets_10: "Chicken Nuggets (10 Stk)",
        cheese_sticks: "Käsesticks",
        mix_plate: "Mix-Teller Kartoffel & Wurst",
        cr_choc: "Schokocroissant",
        cr_caramel: "Karamellcroissant",
        donuts: "Donuts",
        macaroon: "Macaron",
        tube: "Süße Röhre",
        eclair: "Eclair",
        waffles: "Belgische Waffeln mit Obst",
        cola: "Coca-Cola",
        fanta: "Fanta",
        sprite: "Sprite",
        bonakva: "Bonakva",
        sauce_cheese: "Käsesauce",
        sauce_chili: "Süße Chilisauce",
        sauce_bbq: "BBQ-Sauce"
      },
      categories: {
        shawarma: "Schawarma",
        sandwiches: "Sandwiches",
        burgers: "Burger",
        hotdogs: "Hot Dogs",
        fry: "Frittiertes",
        desserts: "Desserts",
        drinks: "Getränke",
        sauces: "Saucen"
      }
    },
    FR: {
      nav: { menu: "MENU", contact: "CONTACT", tea: "THÉ" },
      hero: { title: "NOTRE SÉLECTION" },
      tea: {
        title: "CÉRÉMONIE DU THÉ CHINOIS",
        subtitle: "Prix: 300 UAH",
        description: "Plongez dans une atmosphère de paix et d'harmonie. Nous proposons plus de 40 variétés de thé chinois authentique. Découvrez des millénaires de traditions du thé.",
        features: ["Thé Vert", "Oolong", "Thé Rouge", "Thé Blanc", "Sheng Puer", "Shu Puer"]
      },
      visit: { title: "VISITEZ-NOUS", address: "38, rue Lesi Ukrainki", city: "Kamianets-Podilskyi", route: "ITINÉRAIRE" },
      items: {
        sh_chicken: "Shawarma au Poulet",
        sh_beef: "Shawarma au Boeuf",
        sh_double: "Shawarma Double",
        sh_greek: "Shawarma Grecque",
        snd_pork: "Sandwich Standard (Porc)",
        snd_chicken: "Sandwich Standard (Poulet)",
        brg_classic: "Burger Classique",
        brg_cheese: "Cheeseburger",
        brg_chicken: "Burger au Poulet",
        brg_d_classic: "Double Burger Classique",
        brg_d_cheese: "Double Cheeseburger",
        brg_d_chicken: "Double Burger au Poulet",
        brg_mega: "Mega Burger XXL",
        hd_white_m: "Hot Dog Pain Blanc",
        hd_dark_m: "Hot Dog Pain Noir",
        hd_white_d: "Hot Dog Pain Blanc",
        hd_dark_d: "Hot Dog Pain Noir",
        fries_100: "Frites Croustillantes (100g)",
        fries_150: "Frites Croustillantes (150g)",
        nuggets_7: "Nuggets de Poulet (7pcs)",
        nuggets_10: "Nuggets de Poulet (10pcs)",
        cheese_sticks: "Bâtonnets de Fromage",
        mix_plate: "Assiette Mixte Pommes & Saucisse",
        cr_choc: "Croissant au Chocolat",
        cr_caramel: "Croissant au Caramel",
        donuts: "Donuts",
        macaroon: "Macaron",
        tube: "Tube Sucré",
        eclair: "Éclair",
        waffles: "Gaufres Belges aux Fruits",
        cola: "Coca-Cola",
        fanta: "Fanta",
        sprite: "Sprite",
        bonakva: "Bonakva",
        sauce_cheese: "Sauce au Fromage",
        sauce_chili: "Sauce Chili Douce",
        sauce_bbq: "Sauce BBQ"
      },
      categories: {
        shawarma: "Shawarma",
        sandwiches: "Sandwichs",
        burgers: "Burgers",
        hotdogs: "Hot-dogs",
        fry: "Fritures",
        desserts: "Desserts",
        drinks: "Boissons",
        sauces: "Sauces"
      }
    }
  };

  get t() {
    return this.translations[this.currentLang()];
  }

  setLang(lang: Lang) {
    this.currentLang.set(lang);
  }
}
